version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./_docker/prod/nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./dhparam:/etc/ssl/certs
    depends_on:
      - telegram-bot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./:/var/www
    depends_on:
      - nginx
    # command: certonly --webroot --webroot-path=/var/www --email sammy@your_domain --agree-tos --no-eff-email --staging -d example.com
