services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TELEGRAM_TOKEN=6746424487:AAHlblC6AOMmtdzikkcCemN69EErSG842hg
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - telegram-bot
